name: checks
on:
  pull_request:
    branches:
      - main

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    container:
      image: nesnds/ndp-deployment-container:2
    steps:
      - name: Copy commit-lint config
        run: cp -r /commit-lint .

      - name: Lint commit messages
        uses: ahmadnassri/action-commit-lint@v1
        with:
          config: ./commit-lint/commitlint.config.js

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Run unit tests
        run: npm run test